/* Generated by Yosys 0.30+16 (git sha1 8b2a00102, gcc 11.3.0-1ubuntu1~22.04.1 -fPIC -Os) */
(* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:1.1-285.10" *)
module encode_stream_sc_module_8(clk, reset, minbits, maxbits, maxprec, minexp, s_bc, s_bp, s_last, s_valid, s_ex_data, s_ex_valid, s_ex_ready, s_ready, m_flush, m_bits_data_tdata, m_bits_data_tlast, m_bits_valid, m_bits_ready);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:231.28-231.46" *)
  wire _010_;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:231.28-231.46" *)
  wire _011_;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:231.28-231.46" *)
  wire _012_;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:231.28-231.46" *)
  wire _013_;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:231.28-231.46" *)
  wire _014_;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:231.28-231.46" *)
  wire _015_;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:231.28-231.46" *)
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  wire _440_;
  wire _441_;
  wire _442_;
  wire _443_;
  wire _444_;
  wire _445_;
  wire _446_;
  wire _447_;
  wire _448_;
  wire _449_;
  wire _450_;
  wire _451_;
  wire _452_;
  wire _453_;
  wire _454_;
  wire _455_;
  wire _456_;
  wire _457_;
  wire _458_;
  wire _459_;
  wire _460_;
  wire _461_;
  wire _462_;
  wire _463_;
  wire _464_;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:38.22-38.44" *)
  wire [31:0] buf_w_scclang_global_4;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:2.21-2.24" *)
  input clk;
  wire clk;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:26.16-26.40" *)
  wire [11:0] cs_scclang_global_0_bits;
  reg [11:0] cs_scclang_global_0_buf;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:24.15-24.41" *)
  reg [6:0] cs_scclang_global_0_planes;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:27.15-27.39" *)
  wire [7:0] cs_scclang_global_0_posr;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:28.15-28.39" *)
  wire [7:0] cs_scclang_global_0_posw;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:23.15-23.39" *)
  reg [6:0] cs_scclang_global_0_prec;
  (* onehot = 32'd1 *)
  reg [4:0] cs_scclang_global_0_s;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:17.23-17.40" *)
  output [63:0] m_bits_data_tdata;
  wire [63:0] m_bits_data_tdata;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:18.22-18.39" *)
  output m_bits_data_tlast;
  wire m_bits_data_tlast;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:20.21-20.33" *)
  input m_bits_ready;
  wire m_bits_ready;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:19.22-19.34" *)
  output m_bits_valid;
  wire m_bits_valid;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:16.22-16.29" *)
  output m_flush;
  wire m_flush;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:5.22-5.29" *)
  input [15:0] maxbits;
  wire [15:0] maxbits;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:6.22-6.29" *)
  input [15:0] maxprec;
  wire [15:0] maxprec;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:45.18-45.41" *)
  wire [11:0] \mc_proc.ts_mc_proc_local_2_bits ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:60.18-60.48" *)
  wire [11:0] \mc_proc.ts_mc_proc_local_2_bits__ref_0 ;
  wire [11:0] \mc_proc.ts_mc_proc_local_2_buf ;
  wire [11:0] \mc_proc.ts_mc_proc_local_2_buf__ref_0 ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:43.17-43.42" *)
  wire [6:0] \mc_proc.ts_mc_proc_local_2_planes ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:59.17-59.49" *)
  wire [6:0] \mc_proc.ts_mc_proc_local_2_planes__ref_0 ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:47.17-47.40" *)
  wire [7:0] \mc_proc.ts_mc_proc_local_2_posw ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:56.17-56.47" *)
  wire [7:0] \mc_proc.ts_mc_proc_local_2_posw__ref_0 ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:4.22-4.29" *)
  input [15:0] minbits;
  wire [15:0] minbits;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:7.28-7.34" *)
  input [15:0] minexp;
  wire [15:0] minexp;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:33.16-33.40" *)
  wire [11:0] ns_scclang_global_1_bits;
  wire [11:0] ns_scclang_global_1_buf;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:31.15-31.41" *)
  wire [6:0] ns_scclang_global_1_planes;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:35.15-35.39" *)
  wire [7:0] ns_scclang_global_1_posw;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:39.22-39.44" *)
  wire [31:0] pos_w_scclang_global_5;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:36.22-36.44" *)
  wire [31:0] pre_w_scclang_global_2;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:3.21-3.26" *)
  input reset;
  wire reset;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:8.21-8.25" *)
  input [5:0] s_bc;
  wire [5:0] s_bc;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:9.22-9.26" *)
  input [32:0] s_bp;
  wire [32:0] s_bp;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:12.22-12.31" *)
  input [10:0] s_ex_data;
  wire [10:0] s_ex_data;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:14.22-14.32" *)
  output s_ex_ready;
  wire s_ex_ready;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:13.21-13.31" *)
  input s_ex_valid;
  wire s_ex_valid;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:10.21-10.27" *)
  input s_last;
  wire s_last;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:15.22-15.29" *)
  output s_ready;
  wire s_ready;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:11.21-11.28" *)
  input s_valid;
  wire s_valid;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:234.122-234.123" *)
  wire [15:0] \sc_dt__sc_max_func_1$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:83$3.b ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:227.82-227.83" *)
  wire [15:0] \sc_dt__sc_min_func_0$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:83$4.a ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:227.104-227.105" *)
  wire [15:0] \sc_dt__sc_min_func_0$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:83$4.b ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:220.82-220.83" *)
  wire [11:0] \sc_dt__sc_min_func_4$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:171$8.a ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:220.104-220.105" *)
  wire [11:0] \sc_dt__sc_min_func_4$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:171$8.b ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:278.82-278.83" *)
  wire [15:0] \sc_dt__sc_min_func_5$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:244$10.a ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:278.104-278.105" *)
  wire [15:0] \sc_dt__sc_min_func_5$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:244$10.b ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:278.82-278.83" *)
  wire [15:0] \sc_dt__sc_min_func_5$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:244$6.a ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:278.104-278.105" *)
  wire [15:0] \sc_dt__sc_min_func_5$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:244$6.b ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:37.22-37.44" *)
  wire [31:0] tbc_w_scclang_global_3;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.305-256.309" *)
  wire \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.done ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.224-256.231" *)
  wire [11:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_bits ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.466-256.480" *)
  wire [11:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_bits__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.197-256.203" *)
  wire [127:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_buf ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.432-256.445" *)
  wire [127:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_buf__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.166-256.175" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_planes ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.394-256.410" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_planes__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.251-256.258" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_posr ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.500-256.514" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_posr__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.278-256.285" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_posw ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.534-256.548" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_posw__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.139-256.146" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_prec ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.360-256.374" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_prec__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.115-256.119" *)
  wire [2:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_s ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.329-256.340" *)
  wire [2:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_s__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.305-256.309" *)
  wire \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.done ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.224-256.231" *)
  wire [11:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_bits ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.466-256.480" *)
  wire [11:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_bits__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.197-256.203" *)
  wire [127:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_buf ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.432-256.445" *)
  wire [127:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_buf__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.166-256.175" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_planes ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.394-256.410" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_planes__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.251-256.258" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_posr ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.500-256.514" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_posr__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.278-256.285" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_posw ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.534-256.548" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_posw__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.139-256.146" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_prec ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.360-256.374" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_prec__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.115-256.119" *)
  wire [2:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_s ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:256.329-256.340" *)
  wire [2:0] \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_s__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.307-241.309" *)
  wire [11:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.bc ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.331-241.333" *)
  wire [127:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.bp ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.225-241.232" *)
  wire [11:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_bits ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.490-241.504" *)
  wire [11:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_bits__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.198-241.204" *)
  wire [127:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_buf ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.456-241.469" *)
  wire [127:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_buf__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.167-241.176" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_planes ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.418-241.434" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_planes__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.252-241.259" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_posr ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.524-241.538" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_posr__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.279-241.286" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_posw ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.558-241.572" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_posw__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.140-241.147" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_prec ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.384-241.398" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_prec__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.116-241.120" *)
  wire [2:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_s ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.353-241.364" *)
  wire [2:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_s__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.307-241.309" *)
  wire [11:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.bc ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.225-241.232" *)
  wire [11:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_bits ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.490-241.504" *)
  wire [11:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_bits__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.198-241.204" *)
  wire [127:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_buf ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.456-241.469" *)
  wire [127:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_buf__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.167-241.176" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_planes ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.418-241.434" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_planes__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.252-241.259" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_posr ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.524-241.538" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_posr__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.279-241.286" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_posw ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.558-241.572" *)
  wire [7:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_posw__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.140-241.147" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_prec ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.384-241.398" *)
  wire [6:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_prec__ref_0 ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.116-241.120" *)
  wire [2:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_s ;
  (* nosync = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:241.353-241.364" *)
  wire [2:0] \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_s__ref_0 ;
  assign _017_ = ~maxprec[0];
  assign _018_ = ~(minexp[0] ^ s_ex_data[0]);
  assign _019_ = ~(minexp[13] | minexp[12]);
  assign _020_ = ~minexp[11];
  assign _021_ = s_ex_data[10] & ~(minexp[10]);
  assign _022_ = ~(_021_ & _020_);
  assign _023_ = _021_ ^ _020_;
  assign _024_ = minexp[10] ^ s_ex_data[10];
  assign _025_ = s_ex_data[9] & ~(minexp[9]);
  assign _026_ = _024_ | ~(_025_);
  assign _027_ = _023_ & ~(_026_);
  assign _028_ = _022_ & ~(_027_);
  assign _029_ = _025_ ^ _024_;
  assign _030_ = _023_ & ~(_029_);
  assign _031_ = ~(minexp[9] ^ s_ex_data[9]);
  assign _032_ = s_ex_data[8] & ~(minexp[8]);
  assign _033_ = ~(_032_ & _031_);
  assign _034_ = _032_ ^ _031_;
  assign _035_ = minexp[8] ^ s_ex_data[8];
  assign _036_ = s_ex_data[7] & ~(minexp[7]);
  assign _037_ = _035_ | ~(_036_);
  assign _038_ = _034_ & ~(_037_);
  assign _039_ = _033_ & ~(_038_);
  assign _040_ = _030_ & ~(_039_);
  assign _041_ = _028_ & ~(_040_);
  assign _042_ = _036_ ^ _035_;
  assign _043_ = _034_ & ~(_042_);
  assign _044_ = _043_ & _030_;
  assign _045_ = ~(minexp[7] ^ s_ex_data[7]);
  assign _046_ = s_ex_data[6] & ~(minexp[6]);
  assign _047_ = ~(_046_ & _045_);
  assign _048_ = _046_ ^ _045_;
  assign _049_ = minexp[6] ^ s_ex_data[6];
  assign _050_ = s_ex_data[5] & ~(minexp[5]);
  assign _051_ = _049_ | ~(_050_);
  assign _052_ = _048_ & ~(_051_);
  assign _053_ = _047_ & ~(_052_);
  assign _054_ = _050_ ^ _049_;
  assign _055_ = _048_ & ~(_054_);
  assign _056_ = ~(minexp[5] ^ s_ex_data[5]);
  assign _057_ = s_ex_data[4] & ~(minexp[4]);
  assign _058_ = ~(_057_ & _056_);
  assign _059_ = _057_ ^ _056_;
  assign _060_ = minexp[4] ^ s_ex_data[4];
  assign _061_ = s_ex_data[3] & ~(minexp[3]);
  assign _062_ = _060_ | ~(_061_);
  assign _063_ = _059_ & ~(_062_);
  assign _064_ = _058_ & ~(_063_);
  assign _065_ = _055_ & ~(_064_);
  assign _066_ = _053_ & ~(_065_);
  assign _067_ = _061_ ^ _060_;
  assign _068_ = _059_ & ~(_067_);
  assign _069_ = _068_ & _055_;
  assign _070_ = minexp[3] ^ s_ex_data[3];
  assign _071_ = minexp[2] & ~(s_ex_data[2]);
  assign _072_ = _071_ | _070_;
  assign _073_ = _071_ ^ _070_;
  assign _074_ = ~(minexp[2] ^ s_ex_data[2]);
  assign _075_ = minexp[1] & ~(s_ex_data[1]);
  assign _076_ = _075_ | _074_;
  assign _077_ = _073_ & ~(_076_);
  assign _078_ = _072_ & ~(_077_);
  assign _079_ = ~(_075_ ^ _074_);
  assign _080_ = _073_ & ~(_079_);
  assign _081_ = ~(minexp[1] ^ s_ex_data[1]);
  assign _082_ = minexp[0] & ~(s_ex_data[0]);
  assign _083_ = _082_ | _081_;
  assign _084_ = _080_ & ~(_083_);
  assign _085_ = _078_ & ~(_084_);
  assign _086_ = _069_ & ~(_085_);
  assign _087_ = _066_ & ~(_086_);
  assign _088_ = _044_ & ~(_087_);
  assign _089_ = _041_ & ~(_088_);
  assign _090_ = _019_ & ~(_089_);
  assign _091_ = _090_ & ~(minexp[14]);
  assign _092_ = ~(_091_ ^ minexp[15]);
  assign _093_ = ~(_090_ ^ minexp[14]);
  assign _094_ = ~_093_;
  assign _095_ = _094_ & ~(_092_);
  assign _096_ = _089_ | minexp[12];
  assign _097_ = _096_ ^ minexp[13];
  assign _098_ = _089_ ^ minexp[12];
  assign _099_ = _098_ | _097_;
  assign _100_ = _095_ & ~(_099_);
  assign _101_ = _043_ & ~(_087_);
  assign _102_ = _039_ & ~(_101_);
  assign _103_ = ~(_102_ | _029_);
  assign _104_ = _103_ | ~(_026_);
  assign _105_ = _104_ ^ _023_;
  assign _106_ = _102_ ^ _029_;
  assign _107_ = _106_ | _105_;
  assign _108_ = ~(_087_ | _042_);
  assign _109_ = _108_ | ~(_037_);
  assign _110_ = _109_ ^ _034_;
  assign _111_ = _087_ ^ _042_;
  assign _112_ = _111_ | _110_;
  assign _113_ = _112_ | _107_;
  assign _114_ = _100_ & ~(_113_);
  assign _115_ = _068_ & ~(_085_);
  assign _116_ = _064_ & ~(_115_);
  assign _117_ = ~(_116_ | _054_);
  assign _118_ = _117_ | ~(_051_);
  assign _119_ = _118_ ^ _048_;
  assign _120_ = _116_ ^ _054_;
  assign _121_ = _120_ | _119_;
  assign _122_ = ~(_085_ | _067_);
  assign _123_ = _122_ | ~(_062_);
  assign _124_ = _123_ ^ _059_;
  assign _125_ = _085_ ^ _067_;
  assign _126_ = _125_ | _124_;
  assign _127_ = _126_ | _121_;
  assign _128_ = ~(_083_ | _079_);
  assign _129_ = _128_ | ~(_076_);
  assign _130_ = _129_ ^ _073_;
  assign _131_ = _083_ ^ _079_;
  assign _132_ = _131_ | _130_;
  assign _133_ = ~_018_;
  assign _134_ = _082_ ^ _081_;
  assign _135_ = _134_ | _133_;
  assign _136_ = _135_ | _132_;
  assign _137_ = _136_ | _127_;
  assign _138_ = _114_ & ~(_137_);
  assign _139_ = _138_ | _092_;
  assign _140_ = _139_ | _018_;
  assign _141_ = _140_ ^ maxprec[0];
  assign _142_ = ~maxprec[1];
  assign _143_ = _134_ & ~(_139_);
  assign _144_ = _143_ ^ _142_;
  assign _145_ = ~(_144_ & _141_);
  assign _146_ = ~maxprec[2];
  assign _147_ = _131_ & ~(_139_);
  assign _148_ = _147_ ^ _146_;
  assign _149_ = ~maxprec[3];
  assign _150_ = _130_ & ~(_139_);
  assign _151_ = _150_ ^ _149_;
  assign _152_ = _151_ & _148_;
  assign _153_ = _152_ & ~(_145_);
  assign _154_ = ~maxprec[4];
  assign _155_ = _125_ & ~(_139_);
  assign _156_ = _155_ ^ _154_;
  assign _157_ = ~maxprec[5];
  assign _158_ = _124_ & ~(_139_);
  assign _159_ = _158_ ^ _157_;
  assign _160_ = _159_ & _156_;
  assign _161_ = _120_ & ~(_139_);
  assign _162_ = _161_ ^ maxprec[6];
  assign _163_ = _119_ & ~(_139_);
  assign _164_ = _163_ ^ maxprec[7];
  assign _165_ = _164_ | _162_;
  assign _166_ = _160_ & ~(_165_);
  assign _167_ = ~(_166_ & _153_);
  assign _168_ = ~maxprec[14];
  assign _169_ = _093_ & ~(_139_);
  assign _170_ = _169_ ^ _168_;
  assign _171_ = _092_ & ~(_139_);
  assign _172_ = _171_ ^ maxprec[15];
  assign _173_ = _170_ & ~(_172_);
  assign _174_ = ~maxprec[13];
  assign _175_ = _097_ & ~(_139_);
  assign _176_ = _175_ ^ _174_;
  assign _177_ = ~maxprec[12];
  assign _178_ = _098_ & ~(_139_);
  assign _179_ = _178_ ^ _177_;
  assign _180_ = ~(_179_ & _176_);
  assign _181_ = _173_ & ~(_180_);
  assign _182_ = ~maxprec[11];
  assign _183_ = _105_ & ~(_139_);
  assign _184_ = _183_ ^ _182_;
  assign _185_ = _106_ & ~(_139_);
  assign _186_ = _185_ ^ maxprec[10];
  assign _187_ = _184_ & ~(_186_);
  assign _188_ = ~maxprec[9];
  assign _189_ = _110_ & ~(_139_);
  assign _190_ = _189_ ^ _188_;
  assign _191_ = ~maxprec[8];
  assign _192_ = _111_ & ~(_139_);
  assign _193_ = _192_ ^ _191_;
  assign _194_ = _193_ & _190_;
  assign _195_ = ~(_194_ & _187_);
  assign _196_ = _181_ & ~(_195_);
  assign _197_ = _196_ & ~(_167_);
  assign _198_ = _171_ | ~(maxprec[15]);
  assign _199_ = _169_ | _168_;
  assign _200_ = ~(_199_ | _172_);
  assign _201_ = _198_ & ~(_200_);
  assign _202_ = _175_ | _174_;
  assign _203_ = _178_ | _177_;
  assign _204_ = _176_ & ~(_203_);
  assign _205_ = _202_ & ~(_204_);
  assign _206_ = _173_ & ~(_205_);
  assign _207_ = _201_ & ~(_206_);
  assign _208_ = _183_ | _182_;
  assign _209_ = _185_ | ~(maxprec[10]);
  assign _210_ = _184_ & ~(_209_);
  assign _211_ = _208_ & ~(_210_);
  assign _212_ = _189_ | _188_;
  assign _213_ = _192_ | _191_;
  assign _214_ = _190_ & ~(_213_);
  assign _215_ = _212_ & ~(_214_);
  assign _216_ = _187_ & ~(_215_);
  assign _217_ = _211_ & ~(_216_);
  assign _218_ = _181_ & ~(_217_);
  assign _219_ = _207_ & ~(_218_);
  assign _220_ = _163_ | ~(maxprec[7]);
  assign _221_ = _161_ | ~(maxprec[6]);
  assign _222_ = ~(_221_ | _164_);
  assign _223_ = _220_ & ~(_222_);
  assign _224_ = _158_ | _157_;
  assign _225_ = _155_ | _154_;
  assign _226_ = _159_ & ~(_225_);
  assign _227_ = _224_ & ~(_226_);
  assign _228_ = ~(_227_ | _165_);
  assign _229_ = _223_ & ~(_228_);
  assign _230_ = _150_ | _149_;
  assign _231_ = _147_ | _146_;
  assign _232_ = _151_ & ~(_231_);
  assign _233_ = _230_ & ~(_232_);
  assign _234_ = _143_ | _142_;
  assign _235_ = _017_ & ~(_140_);
  assign _236_ = _144_ & ~(_235_);
  assign _237_ = _234_ & ~(_236_);
  assign _238_ = _152_ & ~(_237_);
  assign _239_ = _233_ & ~(_238_);
  assign _240_ = _166_ & ~(_239_);
  assign _241_ = _229_ & ~(_240_);
  assign _242_ = _196_ & ~(_241_);
  assign _243_ = _219_ & ~(_242_);
  assign _244_ = _243_ | _197_;
  assign _245_ = _244_ ? _017_ : _140_;
  assign _010_ = ~_245_;
  assign _011_ = _244_ ? maxprec[1] : _143_;
  assign _012_ = _244_ ? maxprec[2] : _147_;
  assign _013_ = _244_ ? maxprec[3] : _150_;
  assign _014_ = _244_ ? maxprec[4] : _155_;
  assign _015_ = _244_ ? maxprec[5] : _158_;
  assign _016_ = _244_ ? maxprec[6] : _161_;
  assign _246_ = cs_scclang_global_0_s[3] & reset;
  assign _247_ = ~reset;
  assign _248_ = cs_scclang_global_0_prec[0] ^ cs_scclang_global_0_planes[0];
  assign _249_ = cs_scclang_global_0_prec[1] ^ cs_scclang_global_0_planes[1];
  assign _250_ = ~(_249_ | _248_);
  assign _251_ = ~(cs_scclang_global_0_prec[3] ^ cs_scclang_global_0_planes[3]);
  assign _252_ = cs_scclang_global_0_prec[2] ^ cs_scclang_global_0_planes[2];
  assign _253_ = _252_ | ~(_251_);
  assign _254_ = _250_ & ~(_253_);
  assign _255_ = ~(cs_scclang_global_0_prec[5] ^ cs_scclang_global_0_planes[5]);
  assign _256_ = cs_scclang_global_0_prec[4] ^ cs_scclang_global_0_planes[4];
  assign _257_ = _255_ & ~(_256_);
  assign _258_ = cs_scclang_global_0_prec[6] ^ cs_scclang_global_0_planes[6];
  assign _259_ = ~_258_;
  assign _260_ = ~(_259_ & _257_);
  assign _261_ = _254_ & ~(_260_);
  assign _262_ = cs_scclang_global_0_planes[6] | ~(cs_scclang_global_0_prec[6]);
  assign _263_ = cs_scclang_global_0_planes[5] | ~(cs_scclang_global_0_prec[5]);
  assign _264_ = cs_scclang_global_0_planes[4] | ~(cs_scclang_global_0_prec[4]);
  assign _265_ = _255_ & ~(_264_);
  assign _266_ = _263_ & ~(_265_);
  assign _267_ = cs_scclang_global_0_planes[3] | ~(cs_scclang_global_0_prec[3]);
  assign _268_ = cs_scclang_global_0_planes[2] | ~(cs_scclang_global_0_prec[2]);
  assign _269_ = _251_ & ~(_268_);
  assign _270_ = _267_ & ~(_269_);
  assign _271_ = cs_scclang_global_0_planes[1] | ~(cs_scclang_global_0_prec[1]);
  assign _272_ = cs_scclang_global_0_prec[0] | ~(cs_scclang_global_0_planes[0]);
  assign _273_ = _272_ & ~(_249_);
  assign _274_ = _271_ & ~(_273_);
  assign _275_ = ~(_274_ | _253_);
  assign _276_ = _270_ & ~(_275_);
  assign _277_ = _257_ & ~(_276_);
  assign _278_ = _266_ & ~(_277_);
  assign _279_ = _259_ & ~(_278_);
  assign _280_ = _262_ & ~(_279_);
  assign _281_ = ~(_280_ | _261_);
  assign _282_ = _281_ | _247_;
  assign _283_ = cs_scclang_global_0_s[2] & ~(_282_);
  assign _284_ = _283_ | _246_;
  assign _285_ = maxbits[0] ^ cs_scclang_global_0_posw[0];
  assign _286_ = _285_ | maxbits[1];
  assign _287_ = ~(maxbits[3] ^ cs_scclang_global_0_posw[2]);
  assign _288_ = maxbits[2] ^ cs_scclang_global_0_posw[2];
  assign _289_ = _287_ & ~(_288_);
  assign _290_ = _289_ & ~(_286_);
  assign _291_ = maxbits[7] | maxbits[6];
  assign _292_ = maxbits[5] | maxbits[4];
  assign _293_ = _292_ | _291_;
  assign _294_ = _293_ | ~(_290_);
  assign _295_ = ~(maxbits[15] | maxbits[14]);
  assign _296_ = maxbits[13] | maxbits[12];
  assign _297_ = _295_ & ~(_296_);
  assign _298_ = maxbits[11] | maxbits[10];
  assign _299_ = maxbits[9] | maxbits[8];
  assign _300_ = _299_ | _298_;
  assign _301_ = _297_ & ~(_300_);
  assign _302_ = _301_ & ~(_294_);
  assign _303_ = maxbits[3] | ~(cs_scclang_global_0_posw[2]);
  assign _304_ = maxbits[2] | ~(cs_scclang_global_0_posw[2]);
  assign _305_ = _287_ & ~(_304_);
  assign _306_ = _303_ & ~(_305_);
  assign _307_ = maxbits[0] & ~(cs_scclang_global_0_posw[0]);
  assign _308_ = _307_ | maxbits[1];
  assign _309_ = _289_ & ~(_308_);
  assign _310_ = _306_ & ~(_309_);
  assign _311_ = _310_ | _293_;
  assign _312_ = _301_ & ~(_311_);
  assign _313_ = _312_ | _302_;
  assign _314_ = _281_ & ~(_313_);
  assign _315_ = _314_ | _247_;
  assign _316_ = ~(cs_scclang_global_0_planes[3] | cs_scclang_global_0_planes[2]);
  assign _317_ = cs_scclang_global_0_planes[1] | cs_scclang_global_0_planes[0];
  assign _318_ = _316_ & ~(_317_);
  assign _319_ = ~cs_scclang_global_0_planes[6];
  assign _320_ = cs_scclang_global_0_planes[5] | cs_scclang_global_0_planes[4];
  assign _321_ = _320_ | _319_;
  assign _322_ = _318_ & ~(_321_);
  assign _323_ = minbits[0] ^ cs_scclang_global_0_posw[0];
  assign _324_ = _323_ | minbits[1];
  assign _325_ = ~(minbits[3] ^ cs_scclang_global_0_posw[2]);
  assign _326_ = minbits[2] ^ cs_scclang_global_0_posw[2];
  assign _327_ = _326_ | ~(_325_);
  assign _328_ = _327_ | _324_;
  assign _329_ = minbits[7] | minbits[6];
  assign _330_ = minbits[5] | minbits[4];
  assign _331_ = _330_ | _329_;
  assign _332_ = _331_ | _328_;
  assign _333_ = minbits[15] | minbits[14];
  assign _334_ = minbits[13] | minbits[12];
  assign _335_ = _334_ | _333_;
  assign _336_ = minbits[11] | minbits[10];
  assign _337_ = minbits[9] | minbits[8];
  assign _338_ = _337_ | _336_;
  assign _339_ = _338_ | _335_;
  assign _340_ = _339_ | _332_;
  assign _341_ = minbits[3] | ~(cs_scclang_global_0_posw[2]);
  assign _342_ = minbits[2] | ~(cs_scclang_global_0_posw[2]);
  assign _343_ = _325_ & ~(_342_);
  assign _344_ = _341_ & ~(_343_);
  assign _345_ = minbits[0] & ~(cs_scclang_global_0_posw[0]);
  assign _346_ = _345_ | minbits[1];
  assign _347_ = ~(_346_ | _327_);
  assign _348_ = _344_ & ~(_347_);
  assign _349_ = _348_ | _331_;
  assign _350_ = ~(_349_ | _339_);
  assign _351_ = _340_ & ~(_350_);
  assign _352_ = _322_ & ~(_351_);
  assign _353_ = _351_ | _314_;
  assign _354_ = cs_scclang_global_0_posw[2] | cs_scclang_global_0_posw[0];
  assign _355_ = _354_ | _353_;
  assign _356_ = _352_ & ~(_355_);
  assign _357_ = _356_ | _315_;
  assign _358_ = cs_scclang_global_0_s[4] & ~(_357_);
  assign _359_ = ~s_valid;
  assign _360_ = ~(cs_scclang_global_0_planes[0] | s_last);
  assign _361_ = _318_ & ~(_320_);
  assign _362_ = cs_scclang_global_0_planes[6] & ~(_361_);
  assign _363_ = _362_ | _322_;
  assign _364_ = _363_ ? cs_scclang_global_0_planes[0] : _360_;
  assign _365_ = s_valid ? _364_ : cs_scclang_global_0_planes[0];
  assign _366_ = ~s_last;
  assign _367_ = ~(cs_scclang_global_0_planes[1] ^ cs_scclang_global_0_planes[0]);
  assign _368_ = _366_ & ~(_367_);
  assign _369_ = _363_ ? cs_scclang_global_0_planes[1] : _368_;
  assign _370_ = s_valid ? _369_ : cs_scclang_global_0_planes[1];
  assign _371_ = _370_ | _365_;
  assign _372_ = ~cs_scclang_global_0_planes[2];
  assign _373_ = cs_scclang_global_0_planes[1] & cs_scclang_global_0_planes[0];
  assign _374_ = _373_ ^ _372_;
  assign _375_ = _366_ & ~(_374_);
  assign _376_ = _363_ ? cs_scclang_global_0_planes[2] : _375_;
  assign _377_ = s_valid ? _376_ : cs_scclang_global_0_planes[2];
  assign _378_ = ~(_373_ & cs_scclang_global_0_planes[2]);
  assign _379_ = _378_ ^ cs_scclang_global_0_planes[3];
  assign _380_ = _366_ & ~(_379_);
  assign _381_ = _363_ ? cs_scclang_global_0_planes[3] : _380_;
  assign _382_ = s_valid ? _381_ : cs_scclang_global_0_planes[3];
  assign _383_ = _382_ | _377_;
  assign _384_ = _383_ | _371_;
  assign _385_ = ~cs_scclang_global_0_planes[4];
  assign _386_ = cs_scclang_global_0_planes[3] & cs_scclang_global_0_planes[2];
  assign _387_ = _386_ & _373_;
  assign _388_ = _387_ ^ _385_;
  assign _389_ = _366_ & ~(_388_);
  assign _390_ = _363_ ? cs_scclang_global_0_planes[4] : _389_;
  assign _391_ = s_valid ? _390_ : cs_scclang_global_0_planes[4];
  assign _392_ = ~(_387_ & cs_scclang_global_0_planes[4]);
  assign _393_ = _392_ ^ cs_scclang_global_0_planes[5];
  assign _394_ = _366_ & ~(_393_);
  assign _395_ = _363_ ? cs_scclang_global_0_planes[5] : _394_;
  assign _396_ = s_valid ? _395_ : cs_scclang_global_0_planes[5];
  assign _397_ = _396_ | _391_;
  assign _398_ = cs_scclang_global_0_planes[5] & cs_scclang_global_0_planes[4];
  assign _399_ = _398_ & _387_;
  assign _400_ = _399_ ^ cs_scclang_global_0_planes[6];
  assign _401_ = _366_ & ~(_400_);
  assign _402_ = _363_ ? _319_ : _401_;
  assign _403_ = s_valid ? _402_ : _319_;
  assign _404_ = _403_ | _397_;
  assign _405_ = _404_ | _384_;
  assign _406_ = ~(_405_ | _351_);
  assign _407_ = _354_ | _351_;
  assign _408_ = _406_ & ~(_407_);
  assign _409_ = _408_ | _247_;
  assign _410_ = cs_scclang_global_0_s[1] & ~(_409_);
  assign _411_ = _410_ | _358_;
  assign _003_ = _411_ | _284_;
  assign _412_ = ~(cs_scclang_global_0_s[3] | cs_scclang_global_0_s[2]);
  assign s_ex_ready = ~_412_;
  assign _413_ = s_ex_valid | ~(reset);
  assign _414_ = cs_scclang_global_0_s[0] & ~(_413_);
  assign _415_ = _315_ | ~(_356_);
  assign _416_ = cs_scclang_global_0_s[4] & ~(_415_);
  assign _417_ = _416_ | _414_;
  assign _418_ = ~(_408_ & reset);
  assign _419_ = cs_scclang_global_0_s[1] & ~(_418_);
  assign _420_ = _419_ | _247_;
  assign _002_ = _420_ | _417_;
  assign _421_ = ~(_314_ & reset);
  assign _422_ = cs_scclang_global_0_s[4] & ~(_421_);
  assign _423_ = ~(_281_ & reset);
  assign _424_ = cs_scclang_global_0_s[2] & ~(_423_);
  assign _004_ = _424_ | _422_;
  assign _006_ = cs_scclang_global_0_s[0] | cs_scclang_global_0_s[2];
  assign _005_ = _006_ | cs_scclang_global_0_s[3];
  assign _425_ = cs_scclang_global_0_s[0] | cs_scclang_global_0_s[3];
  assign _007_ = _425_ | cs_scclang_global_0_s[2];
  assign _008_ = cs_scclang_global_0_s[0] | cs_scclang_global_0_s[1];
  assign _426_ = cs_scclang_global_0_s[1] | ~(cs_scclang_global_0_s[4]);
  assign _009_ = _426_ | cs_scclang_global_0_s[4];
  assign \mc_proc.ts_mc_proc_local_2_buf [1] = cs_scclang_global_0_s[2] & s_ex_data[0];
  assign \mc_proc.ts_mc_proc_local_2_buf [2] = cs_scclang_global_0_s[2] & s_ex_data[1];
  assign \mc_proc.ts_mc_proc_local_2_buf [3] = cs_scclang_global_0_s[2] & s_ex_data[2];
  assign \mc_proc.ts_mc_proc_local_2_buf [4] = cs_scclang_global_0_s[2] & s_ex_data[3];
  assign \mc_proc.ts_mc_proc_local_2_buf [5] = cs_scclang_global_0_s[2] & s_ex_data[4];
  assign \mc_proc.ts_mc_proc_local_2_buf [6] = cs_scclang_global_0_s[2] & s_ex_data[5];
  assign \mc_proc.ts_mc_proc_local_2_buf [7] = cs_scclang_global_0_s[2] & s_ex_data[6];
  assign \mc_proc.ts_mc_proc_local_2_buf [8] = cs_scclang_global_0_s[2] & s_ex_data[7];
  assign \mc_proc.ts_mc_proc_local_2_buf [9] = cs_scclang_global_0_s[2] & s_ex_data[8];
  assign \mc_proc.ts_mc_proc_local_2_buf [10] = cs_scclang_global_0_s[2] & s_ex_data[9];
  assign \mc_proc.ts_mc_proc_local_2_buf [11] = cs_scclang_global_0_s[2] & s_ex_data[10];
  assign _427_ = ~cs_scclang_global_0_s[1];
  assign ns_scclang_global_1_planes[0] = _365_ & ~(_427_);
  assign ns_scclang_global_1_planes[1] = _370_ & ~(_427_);
  assign ns_scclang_global_1_planes[2] = _377_ & ~(_427_);
  assign ns_scclang_global_1_planes[3] = _382_ & ~(_427_);
  assign ns_scclang_global_1_planes[4] = _391_ & ~(_427_);
  assign ns_scclang_global_1_planes[5] = _396_ & ~(_427_);
  assign ns_scclang_global_1_planes[6] = cs_scclang_global_0_s[1] & ~(_403_);
  assign ns_scclang_global_1_bits[0] = cs_scclang_global_0_s[3] & ~(_412_);
  assign ns_scclang_global_1_bits[3] = cs_scclang_global_0_s[2] & ~(_412_);
  assign _428_ = cs_scclang_global_0_s[4] | cs_scclang_global_0_s[1];
  assign _429_ = _363_ & ~(_359_);
  assign _430_ = _429_ | _427_;
  assign _431_ = cs_scclang_global_0_s[4] & ~(s_valid);
  assign _432_ = _430_ & ~(_431_);
  assign s_ready = _428_ & ~(_432_);
  assign _433_ = ~(reset & s_ex_valid);
  assign _434_ = ~(s_ex_data[0] | s_ex_data[1]);
  assign _435_ = s_ex_data[3] | s_ex_data[2];
  assign _436_ = _434_ & ~(_435_);
  assign _437_ = s_ex_data[5] | s_ex_data[4];
  assign _438_ = s_ex_data[7] | s_ex_data[6];
  assign _439_ = _438_ | _437_;
  assign _440_ = _436_ & ~(_439_);
  assign _441_ = s_ex_data[9] | s_ex_data[8];
  assign _442_ = _441_ | s_ex_data[10];
  assign _443_ = _440_ & ~(_442_);
  assign _444_ = _245_ & ~(_011_);
  assign _445_ = _013_ | _012_;
  assign _446_ = _444_ & ~(_445_);
  assign _447_ = _015_ | _014_;
  assign _448_ = _447_ | _016_;
  assign _449_ = _446_ & ~(_448_);
  assign _450_ = ~(_449_ | _443_);
  assign _451_ = _433_ | ~(_450_);
  assign _000_ = cs_scclang_global_0_s[0] & ~(_451_);
  assign _452_ = _450_ | _433_;
  assign _001_ = cs_scclang_global_0_s[0] & ~(_452_);
  assign _453_ = _386_ & ~(_373_);
  assign _454_ = _386_ & ~(_453_);
  assign _455_ = _398_ & ~(_454_);
  assign _456_ = _398_ & ~(_455_);
  assign _457_ = _456_ | cs_scclang_global_0_planes[6];
  assign _458_ = cs_scclang_global_0_planes[0] | ~(cs_scclang_global_0_planes[1]);
  assign _459_ = _386_ & ~(_458_);
  assign _460_ = ~(_398_ & _319_);
  assign _461_ = _459_ & ~(_460_);
  assign _462_ = _461_ | _457_;
  assign _463_ = _462_ | _363_;
  assign _464_ = _463_ | _359_;
  assign m_flush = cs_scclang_global_0_s[1] & ~(_464_);
  reg \m_bits_data_tdata_reg[0] ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:40.3-197.6" *)
  always @*
    if (!_009_) \m_bits_data_tdata_reg[0]  = cs_scclang_global_0_buf[0];
  assign m_bits_data_tdata[0] = \m_bits_data_tdata_reg[0] ;
  reg \m_bits_data_tdata_reg[1] ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:40.3-197.6" *)
  always @*
    if (!_009_) \m_bits_data_tdata_reg[1]  = cs_scclang_global_0_buf[1];
  assign m_bits_data_tdata[1] = \m_bits_data_tdata_reg[1] ;
  reg \m_bits_data_tdata_reg[2] ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:40.3-197.6" *)
  always @*
    if (!_009_) \m_bits_data_tdata_reg[2]  = cs_scclang_global_0_buf[2];
  assign m_bits_data_tdata[2] = \m_bits_data_tdata_reg[2] ;
  reg \m_bits_data_tdata_reg[3] ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:40.3-197.6" *)
  always @*
    if (!_009_) \m_bits_data_tdata_reg[3]  = cs_scclang_global_0_buf[3];
  assign m_bits_data_tdata[3] = \m_bits_data_tdata_reg[3] ;
  reg \m_bits_data_tdata_reg[4] ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:40.3-197.6" *)
  always @*
    if (!_009_) \m_bits_data_tdata_reg[4]  = cs_scclang_global_0_buf[4];
  assign m_bits_data_tdata[4] = \m_bits_data_tdata_reg[4] ;
  reg \m_bits_data_tdata_reg[5] ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:40.3-197.6" *)
  always @*
    if (!_009_) \m_bits_data_tdata_reg[5]  = cs_scclang_global_0_buf[5];
  assign m_bits_data_tdata[5] = \m_bits_data_tdata_reg[5] ;
  reg \m_bits_data_tdata_reg[6] ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:40.3-197.6" *)
  always @*
    if (!_009_) \m_bits_data_tdata_reg[6]  = cs_scclang_global_0_buf[6];
  assign m_bits_data_tdata[6] = \m_bits_data_tdata_reg[6] ;
  reg \m_bits_data_tdata_reg[7] ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:40.3-197.6" *)
  always @*
    if (!_009_) \m_bits_data_tdata_reg[7]  = cs_scclang_global_0_buf[7];
  assign m_bits_data_tdata[7] = \m_bits_data_tdata_reg[7] ;
  reg \m_bits_data_tdata_reg[8] ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:40.3-197.6" *)
  always @*
    if (!_009_) \m_bits_data_tdata_reg[8]  = cs_scclang_global_0_buf[8];
  assign m_bits_data_tdata[8] = \m_bits_data_tdata_reg[8] ;
  reg \m_bits_data_tdata_reg[9] ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:40.3-197.6" *)
  always @*
    if (!_009_) \m_bits_data_tdata_reg[9]  = cs_scclang_global_0_buf[9];
  assign m_bits_data_tdata[9] = \m_bits_data_tdata_reg[9] ;
  reg \m_bits_data_tdata_reg[10] ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:40.3-197.6" *)
  always @*
    if (!_009_) \m_bits_data_tdata_reg[10]  = cs_scclang_global_0_buf[10];
  assign m_bits_data_tdata[10] = \m_bits_data_tdata_reg[10] ;
  reg \m_bits_data_tdata_reg[11] ;
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:40.3-197.6" *)
  always @*
    if (!_009_) \m_bits_data_tdata_reg[11]  = cs_scclang_global_0_buf[11];
  assign m_bits_data_tdata[11] = \m_bits_data_tdata_reg[11] ;
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_buf[1] <= 1'h0;
    else if (_006_) cs_scclang_global_0_buf[1] <= \mc_proc.ts_mc_proc_local_2_buf [1];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_buf[2] <= 1'h0;
    else if (_006_) cs_scclang_global_0_buf[2] <= \mc_proc.ts_mc_proc_local_2_buf [2];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_buf[3] <= 1'h0;
    else if (_006_) cs_scclang_global_0_buf[3] <= \mc_proc.ts_mc_proc_local_2_buf [3];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_buf[4] <= 1'h0;
    else if (_006_) cs_scclang_global_0_buf[4] <= \mc_proc.ts_mc_proc_local_2_buf [4];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_buf[5] <= 1'h0;
    else if (_006_) cs_scclang_global_0_buf[5] <= \mc_proc.ts_mc_proc_local_2_buf [5];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_buf[6] <= 1'h0;
    else if (_006_) cs_scclang_global_0_buf[6] <= \mc_proc.ts_mc_proc_local_2_buf [6];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_buf[7] <= 1'h0;
    else if (_006_) cs_scclang_global_0_buf[7] <= \mc_proc.ts_mc_proc_local_2_buf [7];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_buf[8] <= 1'h0;
    else if (_006_) cs_scclang_global_0_buf[8] <= \mc_proc.ts_mc_proc_local_2_buf [8];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_buf[9] <= 1'h0;
    else if (_006_) cs_scclang_global_0_buf[9] <= \mc_proc.ts_mc_proc_local_2_buf [9];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_buf[10] <= 1'h0;
    else if (_006_) cs_scclang_global_0_buf[10] <= \mc_proc.ts_mc_proc_local_2_buf [10];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_buf[11] <= 1'h0;
    else if (_006_) cs_scclang_global_0_buf[11] <= \mc_proc.ts_mc_proc_local_2_buf [11];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_buf[0] <= 1'h0;
    else if (_007_) cs_scclang_global_0_buf[0] <= cs_scclang_global_0_s[2];
  reg \cs_scclang_global_0_posw_reg[0] ;
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) \cs_scclang_global_0_posw_reg[0]  <= 1'h0;
    else if (_005_) \cs_scclang_global_0_posw_reg[0]  <= ns_scclang_global_1_bits[0];
  assign cs_scclang_global_0_posw[0] = \cs_scclang_global_0_posw_reg[0] ;
  reg \cs_scclang_global_0_posw_reg[2] ;
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) \cs_scclang_global_0_posw_reg[2]  <= 1'h0;
    else if (_005_) \cs_scclang_global_0_posw_reg[2]  <= ns_scclang_global_1_bits[3];
  assign cs_scclang_global_0_posw[2] = \cs_scclang_global_0_posw_reg[2] ;
  always @(posedge clk)
    cs_scclang_global_0_s[0] <= _002_;
  always @(posedge clk)
    cs_scclang_global_0_s[1] <= _003_;
  always @(posedge clk)
    cs_scclang_global_0_s[2] <= _000_;
  always @(posedge clk)
    cs_scclang_global_0_s[3] <= _001_;
  always @(posedge clk)
    cs_scclang_global_0_s[4] <= _004_;
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_prec[0] <= 1'h0;
    else if (cs_scclang_global_0_s[0]) cs_scclang_global_0_prec[0] <= _010_;
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_prec[1] <= 1'h0;
    else if (cs_scclang_global_0_s[0]) cs_scclang_global_0_prec[1] <= _011_;
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_prec[2] <= 1'h0;
    else if (cs_scclang_global_0_s[0]) cs_scclang_global_0_prec[2] <= _012_;
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_prec[3] <= 1'h0;
    else if (cs_scclang_global_0_s[0]) cs_scclang_global_0_prec[3] <= _013_;
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_prec[4] <= 1'h0;
    else if (cs_scclang_global_0_s[0]) cs_scclang_global_0_prec[4] <= _014_;
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_prec[5] <= 1'h0;
    else if (cs_scclang_global_0_s[0]) cs_scclang_global_0_prec[5] <= _015_;
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_prec[6] <= 1'h0;
    else if (cs_scclang_global_0_s[0]) cs_scclang_global_0_prec[6] <= _016_;
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_planes[0] <= 1'h0;
    else if (_008_) cs_scclang_global_0_planes[0] <= ns_scclang_global_1_planes[0];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_planes[1] <= 1'h0;
    else if (_008_) cs_scclang_global_0_planes[1] <= ns_scclang_global_1_planes[1];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_planes[2] <= 1'h0;
    else if (_008_) cs_scclang_global_0_planes[2] <= ns_scclang_global_1_planes[2];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_planes[3] <= 1'h0;
    else if (_008_) cs_scclang_global_0_planes[3] <= ns_scclang_global_1_planes[3];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_planes[4] <= 1'h0;
    else if (_008_) cs_scclang_global_0_planes[4] <= ns_scclang_global_1_planes[4];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_planes[5] <= 1'h0;
    else if (_008_) cs_scclang_global_0_planes[5] <= ns_scclang_global_1_planes[5];
  (* \always_ff  = 32'd1 *)
  (* src = "/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:198.3-219.6" *)
  always @(posedge clk)
    if (!reset) cs_scclang_global_0_planes[6] <= 1'h0;
    else if (_008_) cs_scclang_global_0_planes[6] <= ns_scclang_global_1_planes[6];
  assign buf_w_scclang_global_4 = 32'd128;
  assign cs_scclang_global_0_bits = { 8'h00, cs_scclang_global_0_posw[2], cs_scclang_global_0_posw[2], 1'h0, cs_scclang_global_0_posw[0] };
  assign cs_scclang_global_0_posr = 8'h00;
  assign { cs_scclang_global_0_posw[7:3], cs_scclang_global_0_posw[1] } = { 4'h0, cs_scclang_global_0_posw[2], 1'h0 };
  assign m_bits_data_tdata[63:12] = 52'h0000000000000;
  assign m_bits_data_tlast = 1'h0;
  assign m_bits_valid = 1'h0;
  assign \mc_proc.ts_mc_proc_local_2_bits  = { 8'h00, ns_scclang_global_1_bits[3], ns_scclang_global_1_bits[3], 1'h0, ns_scclang_global_1_bits[0] };
  assign \mc_proc.ts_mc_proc_local_2_bits__ref_0  = { 8'h00, ns_scclang_global_1_bits[3], ns_scclang_global_1_bits[3], 1'h0, ns_scclang_global_1_bits[0] };
  assign \mc_proc.ts_mc_proc_local_2_buf [0] = cs_scclang_global_0_s[2];
  assign \mc_proc.ts_mc_proc_local_2_buf__ref_0  = { \mc_proc.ts_mc_proc_local_2_buf [11:1], cs_scclang_global_0_s[2] };
  assign \mc_proc.ts_mc_proc_local_2_planes  = ns_scclang_global_1_planes;
  assign \mc_proc.ts_mc_proc_local_2_planes__ref_0  = ns_scclang_global_1_planes;
  assign \mc_proc.ts_mc_proc_local_2_posw  = { 4'h0, ns_scclang_global_1_bits[3], ns_scclang_global_1_bits[3], 1'h0, ns_scclang_global_1_bits[0] };
  assign \mc_proc.ts_mc_proc_local_2_posw__ref_0  = { 4'h0, ns_scclang_global_1_bits[3], ns_scclang_global_1_bits[3], 1'h0, ns_scclang_global_1_bits[0] };
  assign { ns_scclang_global_1_bits[11:4], ns_scclang_global_1_bits[2:1] } = { 8'h00, ns_scclang_global_1_bits[3], 1'h0 };
  assign ns_scclang_global_1_buf = { \mc_proc.ts_mc_proc_local_2_buf [11:1], cs_scclang_global_0_s[2] };
  assign ns_scclang_global_1_posw = { 4'h0, ns_scclang_global_1_bits[3], ns_scclang_global_1_bits[3], 1'h0, ns_scclang_global_1_bits[0] };
  assign pos_w_scclang_global_5 = 32'd8;
  assign pre_w_scclang_global_2 = 32'd7;
  assign \sc_dt__sc_max_func_1$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:83$3.b  = 16'hxxxx;
  assign \sc_dt__sc_min_func_0$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:83$4.a  = 16'hxxxx;
  assign \sc_dt__sc_min_func_0$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:83$4.b  = 16'hxxxx;
  assign \sc_dt__sc_min_func_4$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:171$8.a  = 12'hxxx;
  assign \sc_dt__sc_min_func_4$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:171$8.b  = 12'hxxx;
  assign \sc_dt__sc_min_func_5$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:244$10.a  = 16'hxxxx;
  assign \sc_dt__sc_min_func_5$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:244$10.b  = 16'hxxxx;
  assign \sc_dt__sc_min_func_5$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:244$6.a  = 16'hxxxx;
  assign \sc_dt__sc_min_func_5$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:244$6.b  = 16'hxxxx;
  assign tbc_w_scclang_global_3 = 32'd12;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.done  = 1'hx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_bits  = 12'hxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_bits__ref_0  = 12'hxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_buf  = 128'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_buf__ref_0  = 128'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_planes  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_planes__ref_0  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_posr  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_posr__ref_0  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_posw  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_posw__ref_0  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_prec  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_prec__ref_0  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_s  = 3'hx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:139$7.ts_s__ref_0  = 3'hx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.done  = 1'hx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_bits  = 12'hxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_bits__ref_0  = 12'hxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_buf  = 128'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_buf__ref_0  = 128'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_planes  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_planes__ref_0  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_posr  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_posr__ref_0  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_posw  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_posw__ref_0  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_prec  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_prec__ref_0  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_s  = 3'hx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__out_bits_func_3$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:176$11.ts_s__ref_0  = 3'hx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.bc  = 12'hxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.bp  = 128'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_bits  = 12'hxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_bits__ref_0  = 12'hxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_buf  = 128'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_buf__ref_0  = 128'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_planes  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_planes__ref_0  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_posr  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_posr__ref_0  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_posw  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_posw__ref_0  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_prec  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_prec__ref_0  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_s  = 3'hx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:123$5.ts_s__ref_0  = 3'hx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.bc  = 12'hxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_bits  = 12'hxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_bits__ref_0  = 12'hxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_buf  = 128'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_buf__ref_0  = 128'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_planes  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_planes__ref_0  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_posr  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_posr__ref_0  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_posw  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_posw__ref_0  = 8'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_prec  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_prec__ref_0  = 7'hxx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_s  = 3'hx;
  assign \zhw__encode_streamfp_t11_52_2_bits_t64__pack_bits_func_2$func$/siliconcompiler/encode_stream_sc_module_8_return_stmt_removed.sv:172$9.ts_s__ref_0  = 3'hx;
endmodule
