# CLI entry banner autogenerated using pyfiglet.
# >> pyfiglet.figlet_format("SC Server")
banner = r'''
 ____   ____   ____
/ ___| / ___| / ___|  ___ _ ____   _____ _ __
\___ \| |     \___ \ / _ \ '__\ \ / / _ \ '__|
 ___) | |___   ___) |  __/ |   \ V /  __/ |
|____/ \____| |____/ \___|_|    \_/ \___|_|
'''


class NodeStatus():
    '''
    Enum class to help ensure consistent status messages
    '''

    COMPLETED = "completed"
    FAILED = "failed"
    TIMEOUT = "timeout"
    RUNNING = "running"
    QUEUED = "queued"
    PENDING = "pending"
    CANCELED = "canceled"
    REJECTED = "rejected"
