'''
Remote execution over the `v1` API: the client here, the server in
:mod:`siliconcompiler.remote.server`. `Project.run()` reaches `ClientScheduler`
when `option,remote` is set; ``tests/remote/BEHAVIOUR.md`` lists what the client owes.
'''

from siliconcompiler.scheduler import Scheduler
from siliconcompiler.scheduler.error import SCRuntimeError
from siliconcompiler.utils.logging import get_console_formatter


# The step name a remote run logs under.
remote_step_name = 'remote'

# CLI entry banner autogenerated using pyfiglet.
# >> pyfiglet.figlet_format("SC Server")
banner = r'''
 ____   ____   ____
/ ___| / ___| / ___|  ___ _ ____   _____ _ __
\___ \| |     \___ \ / _ \ '__\ \ / / _ \ '__|
 ___) | |___   ___) |  __/ |   \ V /  __/ |
|____/ \____| |____/ \___|_|    \_/ \___|_|
'''


class ClientScheduler(Scheduler):
    '''The scheduler a remote run is handed off to.

    A `Scheduler`, so what can fail locally (an unresolved flow, a missing task
    class, disconnected IO) does, before anything is packed. The steps for
    running nodes here are skipped.
    '''

    def run_core(self) -> None:
        from siliconcompiler.remote.client.run import RemoteRun

        project = self.project
        credentials = Credentials.for_project(project)
        client = Client(credentials, logger=project.logger.getChild("remote"))

        formatter = get_console_formatter(project, True, remote_step_name, None)
        previous = project._logger_console.formatter
        project._logger_console.setFormatter(formatter)
        try:
            RemoteRun(project, client).run()
        except RemoteError as e:
            # A message, not a traceback.
            raise SCRuntimeError(str(e)) from None
        finally:
            project._logger_console.setFormatter(previous)

    def configure_nodes(self) -> None:
        '''Nothing to configure: no node runs here.'''
        return

    def check_manifest(self) -> bool:
        '''The server checks the manifest that arrives with the bytes.'''
        return True


from siliconcompiler.remote.client import (            # noqa: E402
    Client, Credentials, RemoteError, ServerProblem, SessionEnded)


__all__ = [
    "Client",
    "Credentials",
    "RemoteError",
    "ServerProblem",
    "SessionEnded",
    "ClientScheduler",
    "banner",
    "remote_step_name"
]
