'''
Remote execution -- the client, and the server it talks to.

The client speaks the `v1` API and nothing else: it holds a DPoP key pair, signs
a proof on every request, and is told by `GET /v1` what the server can do. The
server lives in :mod:`siliconcompiler.remote.server` and runs as
``python -m siliconcompiler.remote.server``.

`ClientScheduler` is still a placeholder: submitting a job needs the job path,
which is the next phase. See ``tests/remote/BEHAVIOUR.md`` for what the client
this replaces did and what the rewrite owes back.
'''

from siliconcompiler._common import NodeStatus as SCNodeStatus
from siliconcompiler.scheduler import Scheduler
from siliconcompiler.scheduler.error import SCRuntimeError


# Step name to use while logging. The logger sizes its step column against the
# nodes a run will execute, and a remote run has this one extra.
remote_step_name = 'remote'

# CLI entry banner autogenerated using pyfiglet.
# >> pyfiglet.figlet_format("SC Server")
banner = r'''
 ____   ____   ____
/ ___| / ___| / ___|  ___ _ ____   _____ _ __
\___ \| |     \___ \ / _ \ '__\ \ / / _ \ '__|
 ___) | |___   ___) |  __/ |   \ V /  __/ |
|____/ \____| |____/ \___|_|    \_/ \___|_|
'''

_UNAVAILABLE = (
    "submitting a remote job is not available yet: the v1 client can log in and "
    "read this server, but the job path has not landed on this branch"
)


class NodeStatus(SCNodeStatus):
    '''
    Enum class to help ensure consistent status messages
    '''

    # special code for uploaded
    UPLOADED = 'uploaded'


class JobStatus():
    '''
    Enum class to help ensure consistent status messages
    '''

    RUNNING = "running"

    COMPLETED = "completed"
    FAILED = "failed"
    CANCELED = "canceled"
    REJECTED = "rejected"
    TIMEOUT = "timeout"

    UNKNOWN = "unknown"


class ClientScheduler(Scheduler):
    '''
    Placeholder for the scheduler a remote run is handed off to.

    The base class is kept so that a flow which could not run at all still says
    so first -- an undefined flow is reported as an undefined flow rather than
    being masked by the rewrite.
    '''

    def run(self) -> None:
        raise SCRuntimeError(_UNAVAILABLE)


from siliconcompiler.remote.client import (            # noqa: E402
    Client, Credentials, RemoteError, ServerProblem, SessionEnded)


__all__ = [
    "NodeStatus",
    "JobStatus",
    "Client",
    "Credentials",
    "RemoteError",
    "ServerProblem",
    "SessionEnded",
    "ClientScheduler",
    "banner",
    "remote_step_name"
]
