import os
import subprocess
import re
import sys
import siliconcompiler

from siliconcompiler.schema_utils import schema_path

####################################################################
# Make Docs
####################################################################

def make_docs():
    '''
    Morty reads SystemVerilog files and pickles them into a
    single file for easier handling. Optionally it allows to
    re-name modules with a common prefix or suffix. This allows for
    easier management of larger projects (they just become a
    single file). By making them unique they can also depend on
    different versions of the same dependency without namespace
    clashes.

    Documentation: https://github.com/zarubaf/morty

    Sources: https://github.com/zarubaf/morty

    Installation: https://github.com/zarubaf/morty

    '''

    chip = siliconcompiler.Chip()
    chip.set('arg','step','import')
    chip.set('arg','index','<index>')
    setup_tool(chip)
    return chip


################################
# Setup Tool (pre executable)
################################

def setup_tool(chip):
    ''' Per tool function that returns a dynamic options string based on
    the dictionary settings.
    '''

    # Standard Setup
    tool = 'morty'
    step = chip.get('arg','step')
    index = chip.get('arg','index')

    chip.set('eda', tool, step, index, 'exe', tool)
    chip.set('eda', tool, step, index, 'threads', 4)
    chip.set('eda', tool, step, index, 'version', '0.0')

    # output single file to `morty.v`
    chip.add('eda', tool, step, index, 'option', 'cmdline', '-o morty.v')
    # write additional information to `manifest.json`
    chip.add('eda', tool, step, index, 'option', 'cmdline', '--manifest manifest.json')

    for value in chip.get('ydir'):
        chip.add('eda', tool, step, index, 'option', 'cmdline', '--library-dir ' + schema_path(value))
    for value in chip.get('vlib'):
        chip.add('eda', tool, step, index, 'option', 'cmdline', '--library-file ' + schema_path(value))
    for value in chip.get('idir'):
        chip.add('eda', tool, step, index, 'option', 'cmdline', '-I ' + schema_path(value))
    for value in chip.get('define'):
        chip.add('eda', tool, step, index, 'option', 'cmdline', '-D ' + schema_path(value))
    for value in chip.get('source'):
        # only pickle Verilog or SystemVerilog files
        if value.endswith('.v') or value.endswith('.vh') or \
                value.endswith('.sv') or value.endswith('.svh'):
            chip.add('eda', tool, step, index, 'option', 'cmdline', schema_path(value))




################################
#  Custom runtime options
################################

def runtime_options(chip):

    ''' Custom runtime options, returnst list of command line options.
    '''

    step = chip.get('arg','step')
    index = chip.get('arg','index')

    cmdlist = []

    # source files
    for value in chip.get('ydir'):
        cmdlist.append('--library-dir ' + chip.find(value))
    for value in chip.get('vlib'):
        cmdlist.append('--library-file ' + chip.find(value))
    for value in chip.get('idir'):
        cmdlist.append('-I' + chip.find(value))
    for value in chip.get('define'):
        cmdlist.append('-D' + chip.find(value))
    for value in chip.get('source'):
        if value.endswith('.v') or value.endswith('.vh') or \
           value.endswith('.sv') or value.endswith('.svh'):
            cmdlist.append(chip.find(value))

    return cmdlist

################################
# Post_process (post executable)
################################

def post_process(chip, step, index):
    ''' Tool specific function to run after step execution
    '''

    # detect top module by reading the manifest generated by morty
    top = chip.get('design')
    if top == "" and os.isfile("manifest.json"):
        with open("manifest.json", "r") as manifest:
            data = json.load(manifest)
            if len(data["tops"]) > 1:
                chip.logger.error('Multiple top-level modules found during \
                        import, but sc_design was not set')
                sys.exit()
            if len(data["tops"]) <= 0:
                chip.logger.error('No top-level modules found during \
                        import, and sc_design was not set')
                sys.exit()
            top = data["tops"][0]

    # Hand off `morty.v` and `manifest.json` to the next step
    subprocess.run("cp morty.v " + "outputs/" + top + ".v", shell=True)
    subprocess.run("cp manifest.json " + "outputs/", shell=True)

    return 0

##################################################
if __name__ == "__main__":

    # File being executed
    prefix = os.path.splitext(os.path.basename(__file__))[0]
    output = prefix + '.json'

    # create a chip instance
    chip = siliconcompiler.Chip()
    # load configuration
    setup_tool(chip, step='import', index='0')
    # write out results
    chip.writecfg(output)
