# Version number following semver standard.
version = '0.9.6'

# This is the list of significant contributors to SiliconCompiler in
# chronological order.
#
# This does not necessarily list everyone who has contributed code,
# especially since many employees of one corporation may be contributing.
# To see the full list of contributors, see the git revision history
authors = [
    'Andreas Olofsson',
    'William Ransohoff',
    'Noah Moroze',
    'Zachary Yedidia',
    'Massimiliano Giacometti',
    'Kimia Talaei',
    'Peter Gadfort'
]

# CLI entry banner autogenerated using pyfiglet.
# >> pyfiglet.figlet_format("Silicon Compiler")
banner = r'''
 ____  _ _ _                    ____                      _ _
/ ___|(_) (_) ___ ___  _ __    / ___|___  _ __ ___  _ __ (_) | ___ _ __
\___ \| | | |/ __/ _ \| '_ \  | |   / _ \| '_ ` _ \| '_ \| | |/ _ \ '__|
 ___) | | | | (_| (_) | | | | | |__| (_) | | | | | | |_) | | |  __/ |
|____/|_|_|_|\___\___/|_| |_|  \____\___/|_| |_| |_| .__/|_|_|\___|_|
                                                   |_|
'''

# Default input file map for SC with filesets and extensions

# High level languages
_iomap_hll_c = ('c', 'cc', 'cpp', 'c++', 'cp', 'cxx', 'hpp')
_iomap_hll_bvs = ('bvs',)
_iomap_hll_scala = ('scala',)
_iomap_hll_python = ('py',)

# Register transfer languages
_iomap_rtl_verilog = ('v', 'vg', 'sv', 'verilog')
_iomap_rtl_vhdl = ('vhd', 'vhdl')

# Timing libraries
_iomap_timing_liberty = ('lib', 'ccs')

# Layout
_iomap_layout_def = ('def',)
_iomap_layout_lef = ('lef',)
_iomap_layout_gds = ('gds', 'gds2', 'gdsii')
_iomap_layout_oas = ('oas', 'oasis')
_iomap_layout_gerber = ('gbr', 'gerber')

# Netlist
_iomap_netlist_cdl = ('cdl',)
_iomap_netlist_sp = ('sp', 'spice')

# Waveform
_iomap_waveform_vcd = ('vcd',)

# Constraint
_iomap_constraint_sdc = ('sdc', )

# Build default map
default_iomap = {}
default_iomap.update({ext: ('hll', 'c') for ext in _iomap_hll_c})
default_iomap.update({ext: ('hll', 'bvs') for ext in _iomap_hll_bvs})
default_iomap.update({ext: ('hll', 'scala') for ext in _iomap_hll_scala})
default_iomap.update({ext: ('hll', 'python') for ext in _iomap_hll_python})

default_iomap.update({ext: ('rtl', 'verilog') for ext in _iomap_rtl_verilog})
default_iomap.update({ext: ('rtl', 'vhdl') for ext in _iomap_rtl_vhdl})

default_iomap.update({ext: ('timing', 'liberty') for ext in _iomap_timing_liberty})

default_iomap.update({ext: ('layout', 'def') for ext in _iomap_layout_def})
default_iomap.update({ext: ('layout', 'lef') for ext in _iomap_layout_lef})
default_iomap.update({ext: ('layout', 'gds') for ext in _iomap_layout_gds})
default_iomap.update({ext: ('layout', 'oas') for ext in _iomap_layout_oas})
default_iomap.update({ext: ('layout', 'gerber') for ext in _iomap_layout_gerber})

default_iomap.update({ext: ('netlist', 'cdl') for ext in _iomap_netlist_cdl})
default_iomap.update({ext: ('netlist', 'sp') for ext in _iomap_netlist_sp})

default_iomap.update({ext: ('waveform', 'vcd') for ext in _iomap_waveform_vcd})

default_iomap.update({ext: ('constraint', 'sdc') for ext in _iomap_constraint_sdc})
