#!/usr/bin/env python3

# Import the core classes from the siliconcompiler library.
from siliconcompiler import ASIC, Design
# Import a pre-defined target for the FreePDK45 process.
from siliconcompiler.targets import freepdk45_demo


def main():
    '''
    This script demonstrates a Bluespec SystemVerilog (BSV) to GDSII flow.
    It shows that a Bluespec design needs no custom flow: the target reads the
    source language off the design's files and puts the Bluespec compiler in
    front of the standard synthesis, place, and route steps.

    Requires: bsc (Bluespec), yosys, openroad, opensta, klayout; freepdk45 (via lambdapdk)
    '''

    # --- Design Setup ---
    # Create a design schema to hold the project's configuration.
    design = Design("fibone")
    # Set up a 'dataroot' to easily reference local files.
    design.set_dataroot("fibone", __file__)

    # Configure the "rtl" fileset.
    # Note that the source file is a '.bsv' file, not Verilog.
    with design.active_dataroot("fibone"), design.active_fileset("rtl"):
        # The topmodule 'mkFibOne' is the name of the compiled module
        # generated by the Bluespec compiler, not the file name.
        design.set_topmodule("mkFibOne")
        design.add_file("FibOne.bsv")

    # --- Project Setup ---
    # Create a standard ASIC project.
    project = ASIC(design)

    # Tell the project to use the "rtl" fileset we defined.
    project.add_fileset("rtl")

    # --- Target Loading ---
    # Load the target configuration for the FreePDK45 technology. This is the
    # key part of the example: the target picks the flow's front end from the
    # design's sources, so the .bsv file above selects a 'convert' step running
    # the Bluespec compiler (bsc) where a Verilog design would get 'elaborate'.
    # The resulting flow is named 'asicflow-bluespec'. Passing
    # language="bluespec" here would select the same front end explicitly.
    freepdk45_demo(project)

    # --- Execution & Analysis ---
    # Run the flow. SiliconCompiler will execute the 'convert' step first, then
    # proceed with synthesis, place, route, and GDS export.
    project.run()

    # Display a summary of the results (timing, area, etc.).
    project.summary()

    return project


if __name__ == '__main__':
    main()
