###############################
# Reading SC Schema
###############################

source ./sc_manifest.tcl

###############################
# Read Files
###############################

source "$sc_refdir/sc_read_design.tcl"

###############################
# Hand over to the interactive session
###############################

# Nothing is reported here on purpose: the point of this task is to leave a
# populated OpenSTA at its prompt so the user can drive it. OpenSTATask omits
# -exit while has_breakpoint() is true, which OpenTask makes unconditional, so
# reaching the end of this script drops into the shell.
puts "Design ${sc_topmodule} is loaded for corners: $sc_scenarios"
puts "Timing reports are not generated by this task; use report_checks and\
    friends interactively."

if { [sc_cfg_tool_task_get var showexit] } {
    exit
}
