import os
import difflib
import shutil

from typing import Optional

from siliconcompiler.schema import NamedSchema, EditableSchema, Parameter, Scope
from siliconcompiler.schema.utils import trim
from siliconcompiler.utils import sc_open


class Patch(NamedSchema):
    '''
    Schema for a 'patch'.
    '''

    def __init__(self, name: Optional[str] = None):
        '''
        Initializes a new Patch object. The optional name argument is not
        currently used, but is included for future expansion.
        '''
        super().__init__()
        self.set_name(name)

        schema = EditableSchema(self)
        schema.insert(
            'file',
            Parameter(
                'str',
                scope=Scope.GLOBAL,
                shorthelp="File to patch",
                help=trim("""
            File to apply a patch to. The path is relative to the fileset root.""")))

        schema.insert(
            'dataroot',
            Parameter(
                'str',
                scope=Scope.GLOBAL,
                shorthelp="Data root for file to patch",
                help=trim("""
            The data root where the file to patch is located. This is typically the fileset root.""")))

        schema.insert(
            'diff',
            Parameter(
                'str',
                scope=Scope.GLOBAL,
                shorthelp="Unified diff for patch",
                help=trim("""The patch content in ndiff format.
            This format describes the differences between an original and a
            modified file, line by line. It is the format generated by
            `difflib.ndiff()`.

            Each line in the delta begins with a two-letter code:
            '- ': line unique to sequence 1
            '+ ': line unique to sequence 2
            '  ': line common to both sequences
            '? ': line not present in either input sequence (ignored by restore)

            You can generate this delta text using the `create_from_files()`
            method.""")))

    def apply(self, file_to_patch: str) -> None:
        """
        Applies a delta to a file using difflib.restore.
        This avoids dependencies on external command-line tools.

        Args:
            file_to_patch (str): The path to the file to be patched.

        Raises:
            FileNotFoundError: If the file to patch does not exist.
            ValueError: If no diff text is found for this patch.
            IOError: If the patched file could not be written.
        """
        diff_text = self.get('diff')
        if not diff_text:
            raise ValueError("No diff text found for this patch.")

        if not os.path.exists(file_to_patch):
            raise FileNotFoundError(f"File to patch does not exist: {file_to_patch}")

        # Create a backup
        try:
            shutil.copy(file_to_patch, f"{file_to_patch}.orig")
        except Exception as e:
            raise IOError(f"Could not create backup for {file_to_patch}: {e}")

        delta = diff_text.splitlines(keepends=True)

        try:
            # restore() returns a generator which yields the lines of sequence 2
            with open(file_to_patch, 'w', newline='') as f:
                f.writelines(difflib.restore(delta, 2))
        except Exception as e:
            raise IOError(f"Could not write patched file: {file_to_patch} - {e}")

    def create_from_files(self, original_file: str, modified_file: str) -> None:
        """
        Creates a delta from two files using difflib.ndiff and sets the diff field.

        Args:
            original_file (str): The path to the original file.
            modified_file (str): The path to the modified file.
        """
        with sc_open(original_file) as f:
            original_lines = f.readlines()
        with sc_open(modified_file) as f:
            modified_lines = f.readlines()

        self.set('diff', ''.join(difflib.ndiff(original_lines, modified_lines)))
