import os
import subprocess
import re
import sys
from siliconcompiler.schema import schema_istrue
from siliconcompiler.schema import schema_path

################################
# Setup GHDL
################################

def setup_tool(chip, step):
    ''' Sets up default settings on a per step basis
    '''
    # this tool requires that Yosys, GHDL, and the Yosys GHDL plugin all be
    # installed
    chip.logger.debug("Setting up GHDL (via Yosys)")

    chip.add('flow', step, 'threads', '4')
    chip.add('flow', step, 'format', 'cmdline')
    chip.add('flow', step, 'copy', 'false')
    chip.add('flow', step, 'exe', 'yosys')
    chip.add('flow', step, 'vendor', 'ghdl')

################################
# Set GHDL Runtime Options
################################

def setup_options(chip, step):
    ''' Per tool/step function that returns a dynamic options string based on
    the dictionary settings.
    '''

    options = chip.set('flow', step, 'option', [])

    # ghdl is invoked via Yosys by running a command with the format:
    #   yosys -m ghdl -p 'ghdl --std=08 --no-formal sources...; write_ilang ghdl.ilang'
    options.append('-m ghdl')
    options.append('-p \'ghdl')

    options.append('--std=08')
    options.append('--no-formal')

    # parameter overrides
    for value in chip.cfg['define']['value']:
        options.append('-g' + schema_path(value))

    # only use VHDL source files (*.vhd and *.vhdl)
    for value in chip.cfg['source']['value']:
        if value.endswith('.vhd') or value.endswith('.vhdl'):
            options.append(schema_path(value))

    # determine the top modules for the VHDL import:
    # if the `undefined.morty` file is generated by a previous Verilog import,
    # then we use the undefined modules listed in that file as guesses for the
    # VHDL top modules.
    # if `undefined.morty` is not found, we assume the design top lists the
    # single VHDL top module, and return an error if it is not defined.
    modules = ""
    try:
        with open("inputs/undefined.morty", "r") as undefined_file:
            modules = undefined_file.read().strip()
    except FileNotFoundError:
        if len(chip.cfg['design']['value']) < 1:
            chip.logger.error('No top module set')
            return
        modules = chip.cfg['design']['value'][-1]

    # pass the list of top modules to GHDL for elaboration
    options.append('-e ' + modules)

    # generate a .ilang file (Yosys RTLIL) which can be read by Yosys during
    # synthesis along with the Verilog inputs
    options.append('; write_ilang ghdl.ilang\'')

    chip.set('flow', step, 'option', options)

    return options

################################
# Pre and Post Run Commands
################################
def pre_process(chip, step):
    ''' Tool specific function to run before step execution
    '''

def post_process(chip, step):
    ''' Tool specific function to run after step execution
    '''

    topmodule = chip.cfg['design']['value'][-1]
    # pass the RTLIL to the next step
    subprocess.run("cp ghdl.ilang " + "outputs/" + topmodule + ".ilang",
                   shell=True)
    
    # pass any pickled verilog file along as well
    if os.path.isfile("inputs/" + topmodule + ".v"):
        subprocess.run("cp inputs/" + topmodule + ".v" + " outputs/", shell=True)
