#!/usr/bin/env python3
'''Wrapping a design in an IO pad ring.

Takes a RISC-V processor and its SRAM to GDSII inside a full sky130 pad ring:
40 bidirectional signal pads, 16 supply pads, corners, IO fill, bond pads, and a
core power grid tied out to the ring. The pad ring is generated by lambdalib, so
no sky130 cell is named in the RTL.

The processor is picorv32, fetched from its own repository at a pinned commit
rather than copied into this one.

Requires: yosys, openroad, opensta, klayout; skywater130 (via lambdapdk)
'''

from siliconcompiler import ASIC, Design
from siliconcompiler.targets import skywater130_demo

from lambdalib.padring import Padring
from lambdalib.ramlib import Spram

from siliconcompiler.tools.openroad.init_floorplan import InitFloorplanTask
from siliconcompiler.tools.openroad._apr import APRTask, OpenROADPSMParameter
from siliconcompiler.tools.openroad.power_grid import PowerGridTask


class PadringExample(Design):
    '''A RISC-V processor and its memory, wrapped in a pad ring.

    Six filesets, because a pad ring needs more than RTL: the processor, the die
    that joins it to a memory and a ring, the constraints, and three sets of
    physical instructions for OpenROAD.
    '''

    def __init__(self):
        super().__init__("padring")
        self.set_dataroot("padring", __file__)

        # The processor, from upstream at a pinned commit. Fetching beats
        # vendoring: the version is explicit and the source stays where it is
        # maintained.
        self.set_dataroot("picorv32",
                          "git+https://github.com/YosysHQ/picorv32.git",
                          "c0acaebf0d50afc6e4d15ea9973b60f5f4d03c42")

        with self.active_fileset("rtl.cpu"), self.active_dataroot("picorv32"):
            self.set_topmodule("picorv32")
            self.add_file("picorv32.v")

        # The die: processor, memory and the ring that bonds them out. The pad
        # ring generator and the SRAM come in as dependencies rather than as
        # copied RTL.
        with self.active_dataroot("padring"), self.active_fileset("rtl"):
            self.set_topmodule("picorv32_top")
            self.add_idir("rtl")
            self.add_file("rtl/picorv32_top.v")
            self.add_depfileset(self, "rtl.cpu")
            self.add_depfileset(Spram(), "rtl")
            self.add_depfileset(Padring(), "rtl")

        with self.active_dataroot("padring"), self.active_fileset("sdc"):
            self.add_file("padring.sdc")

        # Physical construction, kept in separate filesets so that a
        # different technology can supply its own without touching the RTL.
        with self.active_dataroot("padring"), self.active_fileset("padring.sky130"):
            self.add_file("openroad/padring.tcl")

        with self.active_dataroot("padring"), self.active_fileset("pdn.sky130"):
            self.add_file("openroad/pdn.tcl")

        with self.active_dataroot("padring"), self.active_fileset("globalconns.sky130"):
            self.add_file("openroad/global_connect.tcl")


def setup_project(remote: bool = False) -> ASIC:
    '''Builds the project, and wires the physical filesets to the tasks that read them.'''

    project = ASIC(PadringExample())
    project.add_fileset(["rtl", "sdc"])

    skywater130_demo(project)

    # The three hooks that turn an ordinary ASIC run into one with a pad ring.
    # Each is a task variable rather than a schema key, because it configures one
    # step of the flow rather than the design.
    # Note the asymmetry: the pad ring hook takes a fileset name, while the power
    # grid and global connect hooks take the library that owns the fileset as well.
    InitFloorplanTask.find_task(project).add_openroad_padringfileset("padring.sky130")

    PowerGridTask.find_task(project).add_openroad_powergridfileset("padring", "pdn.sky130")

    for task in APRTask.find_task(project):
        task.add_openroad_globalconnectfileset("padring", "globalconns.sky130")

    # The IO ring is driven by the pads, not by the core's grid, so the power
    # analyser should not expect to find a driver for those nets inside the core.
    for task in OpenROADPSMParameter.find_task(project):
        task.add_openroad_psmskipnets("*io*")

    # The ring needs about 1520um a side (fourteen cells plus two corners), but the
    # memory needs more: sky130's SRAM macro is 1041um wide at any depth and needs
    # a placement channel, so with a 250um margin to clear the pads the macro is
    # what sets this die, not the ring.
    project.constraint.area.set_dieoutline(1900, 1900, coremargin=250)

    # Keep placement off the memory macro so its pins stay reachable.
    project.constraint.component.make_component("*sram*memory").set_halo(5.0, 5.0)

    if remote:
        project.option.set_remote(True)

    return project


def main():
    project = setup_project()
    project.run()
    project.summary()
    project.show()


if __name__ == '__main__':
    main()
