import json

import pytest

from conftest import outcome

from siliconcompiler.remote import environment
from siliconcompiler.remote.environment import EnvironmentFileError


# A node's Python environment, as a file (surface D131). The format is closed,
# and what is asserted is that it admits exactly what it says: a line pip would
# read one way and this grammar another has no route through.


def parse(*lines):
    return environment.parse(("\n".join(lines) + "\n").encode())


###########################
# The format
###########################

def test_what_the_format_takes():
    parsed = parse(
        "# generated by SiliconCompiler",
        "",
        "--index-url https://pypi.org/simple/",
        "--extra-index-url https://files.pythonhosted.org/",
        "numpy==2.0.1",
        "cocotb-bus[extra,other]==0.2.1 ; python_version >= '3.10'",
        "pyuvm==3.0.0   # a comment after whitespace",
    )

    assert [str(pin) for pin in parsed.pins] == [
        "numpy==2.0.1",
        "cocotb-bus[extra,other]==0.2.1 ; python_version >= '3.10'",
        "pyuvm==3.0.0"]
    assert parsed.indexes == ["https://pypi.org/simple/", "https://files.pythonhosted.org/"]


@pytest.mark.parametrize("line", [
    "numpy>=2.0",                              # a range
    "numpy==2.*",                              # a prefix
    "numpy===2.0",                             # arbitrary equality
    "numpy==2.0,<3",                           # two clauses
    "numpy",                                   # no version at all
    "numpy @ https://example.com/numpy.whl",   # a URL requirement
    "git+https://github.com/x/y.git",          # a VCS one
    "./local/package",                         # a local path
    "-e .",                                    # an editable
    "-i https://pypi.org/simple/",             # the short spelling
    "--index-url=https://pypi.org/simple/",    # the `=` spelling
    "--find-links https://example.com/",
    "--trusted-host example.com",
    "-r other.txt", "-c constraints.txt",
    "numpy==2.0 --hash=sha256:abc",
    "numpy==2.0 \\",                           # a continuation
    "numpy==2.0#no-space-before-it",
    "numpy==2.0 ; not a marker (",
    "--index-url https://user:token@example.com/simple/",   # a credential
    "--index-url ftp://example.com/",
])
def test_everything_else_is_refused(line):
    with pytest.raises(EnvironmentFileError):
        parse(line)


def test_a_file_may_list_nothing():
    '''A node whose only additions are forwarded packages still has one.'''
    parsed = parse("# Generated by SiliconCompiler", "", "   # and nothing else")

    assert parsed.pins == [] and parsed.indexes == []


def test_each_name_once_as_pep_503_sees_it():
    with pytest.raises(EnvironmentFileError, match="twice"):
        parse("Cocotb_Bus==0.2.1", "cocotb-bus==0.2.1")


def test_one_replacing_index_and_any_number_of_extra():
    with pytest.raises(EnvironmentFileError, match="second --index-url"):
        parse("--index-url https://a.example/", "--index-url https://b.example/")
    assert len(parse(*[f"--extra-index-url https://{n}.example/" for n in "abc"])
               .extra_index_urls) == 3


def test_the_bounds():
    with pytest.raises(EnvironmentFileError, match="lines"):
        parse(*[f"p{n}==1.0" for n in range(environment.MAX_LINES + 1)])
    with pytest.raises(EnvironmentFileError, match="bytes"):
        environment.parse(b"#" * (environment.MAX_BYTES + 1))
    with pytest.raises(EnvironmentFileError, match="UTF-8"):
        environment.parse(b"\xff\xfe==1.0\n")


def test_what_is_rendered_is_what_is_parsed():
    '''A builder writes its own file from what parsed; it reads back the same.'''
    parsed = parse("--extra-index-url https://files.pythonhosted.org/",
                   "numpy==2.0.1", "pyuvm==3.0.0 ; sys_platform == 'linux'")

    again = environment.parse(environment.render(
        parsed.pins, parsed.index_url, parsed.extra_index_urls,
        header="written by the builder").encode())

    assert again == parsed


###########################
# At submit
###########################

pytest.importorskip("flask", reason="the server extra is not installed")


def carrying(job_archive, text, node=("stepone", "0")):
    return job_archive(extra={environment.path_for(*node): text.encode()})


def submitted(server_client, key, token, archive):
    from test_server_jobs import stage, submit

    path, digest, size = archive
    job = stage(server_client, key, token, path, size)
    return outcome(server_client, key, token,
                   submit(server_client, key, token, job["id"], digest, size))


def slug(response):
    return (response.get_json().get("type") or "").rsplit("/", 1)[-1]


@pytest.fixture
def builds(server):
    '''A deployment that advertises `python.env` -- what this server will
    once it can build one; nothing here builds anything.'''
    server.config["SC_CONFIG"]._values["features"] = \
        server.config["SC_CONFIG"]["features"] + ["python.env"]
    return server


def test_a_job_carrying_an_environment_needs_python_env(
        server, server_client, key, token, job_archive):
    '''The file's presence is the declaration: the backstop for a job that did
    not say so at create.'''
    response = submitted(server_client, key, token,
                         carrying(job_archive, "numpy==2.0.1\n"))

    assert response.status_code == 501
    assert (slug(response), response.get_json()["feature"]) == \
        ("feature-unsupported", "python.env")


def test_a_line_outside_the_format_is_an_archive_refusal(
        builds, server_client, key, token, job_archive):
    response = submitted(server_client, key, token,
                         carrying(job_archive, "numpy>=2.0\n"))

    assert response.status_code == 422
    assert slug(response) == "archive-rejected"
    assert response.get_json()["reason"] == "environment_file"
    assert "line 1" in response.get_json()["detail"]


def test_a_file_for_no_node_is_refused(builds, server_client, key, token, job_archive):
    response = submitted(server_client, key, token,
                         carrying(job_archive, "numpy==2.0.1\n", node=("nosuch", "0")))

    assert response.get_json()["reason"] == "environment_file"


def test_an_index_off_the_allowlist_is_refused_naming_it(
        builds, server_client, key, token, job_archive):
    response = submitted(server_client, key, token, carrying(
        job_archive, "--extra-index-url https://pkgs.example.com/simple/\nnumpy==2.0.1\n"))

    assert response.status_code == 422
    assert slug(response) == "software-unavailable"
    assert response.get_json()["reason"] == "index-not-allowed"
    assert "pkgs.example.com" in response.get_json()["detail"]


def test_a_well_formed_environment_passes(builds, server_client, key, token, job_archive,
                                          dispatcher):
    response = submitted(server_client, key, token, carrying(
        job_archive, "# generated\n--index-url https://pypi.org/simple/\nnumpy==2.0.1\n"))

    assert response.status_code == 202, response.get_json()


def test_the_deployment_does_not_advertise_what_it_cannot_build(tmp_path):
    '''No builder yet: where nodes run in containers there is nothing to
    build an environment with.'''
    from siliconcompiler.remote.server.config import Config

    (tmp_path / "config.json").write_text(json.dumps(
        {"features": ["python.env"], "containers": True}))
    with pytest.raises(ValueError, match="python.env"):
        Config.load(tmp_path)


@pytest.fixture
def dispatcher(server):
    from test_server_jobs import FakeDispatcher

    fake = FakeDispatcher()
    server.config["SC_JOBS"]._dispatcher = fake
    return fake
