import json

import pytest

from conftest import outcome

from siliconcompiler.remote import environment
from siliconcompiler.remote.environment import EnvironmentFileError


# A node's Python environment, as a file (surface D131). The format is closed,
# and what is asserted is that it admits exactly what it says: a line pip would
# read one way and this grammar another has no route through.


def parse(*lines):
    return environment.parse(("\n".join(lines) + "\n").encode())


###########################
# The format
###########################

def test_what_the_format_takes():
    parsed = parse(
        "# generated by SiliconCompiler",
        "",
        "numpy==2.0.1",
        "cocotb-bus[extra,other]==0.2.1 ; python_version >= '3.10'",
        "pyuvm==3.0.0   # a comment after whitespace",
    )

    assert [str(pin) for pin in parsed.pins] == [
        "numpy==2.0.1",
        "cocotb-bus[extra,other]==0.2.1 ; python_version >= '3.10'",
        "pyuvm==3.0.0"]


def test_the_file_is_where_the_contract_puts_it():
    assert environment.path_for("sim", "0") == "sc_python/nodes/sim/0/requirements.txt"
    assert environment.packages_path() == "sc_python/packages"


@pytest.mark.parametrize("line", [
    "numpy>=2.0",                              # a range
    "numpy==2.*",                              # a prefix
    "numpy===2.0",                             # arbitrary equality
    "numpy==2.0,<3",                           # two clauses
    "numpy",                                   # no version at all
    "numpy @ https://example.com/numpy.whl",   # a URL requirement
    "git+https://github.com/x/y.git",          # a VCS one
    "./local/package",                         # a local path
    "-e .",                                    # an editable
    "-i https://pypi.org/simple/",             # the short spelling
    "--index-url=https://pypi.org/simple/",    # the `=` spelling
    "--find-links https://example.com/",
    "--trusted-host example.com",
    "-r other.txt", "-c constraints.txt",
    "numpy==2.0 --hash=sha256:abc",
    "numpy==2.0 \\",                           # a continuation
    "numpy==2.0#no-space-before-it",
    "numpy==2.0 ; not a marker (",
    # 🔴 No line names an index: every package comes from the deployment's own.
    "--index-url https://pypi.org/simple/",
    "--extra-index-url https://files.pythonhosted.org/",
    "--index-url https://user:token@example.com/simple/",
])
def test_everything_else_is_refused(line):
    with pytest.raises(EnvironmentFileError):
        parse(line)


def test_a_file_may_list_nothing():
    '''Legal, though the client writes none for a node with no line.'''
    parsed = parse("# Generated by SiliconCompiler", "", "   # and nothing else")

    assert parsed.pins == []


def test_each_name_once_as_pep_503_sees_it():
    with pytest.raises(EnvironmentFileError, match="twice"):
        parse("Cocotb_Bus==0.2.1", "cocotb-bus==0.2.1")


def test_the_bounds():
    with pytest.raises(EnvironmentFileError, match="lines"):
        parse(*[f"p{n}==1.0" for n in range(environment.MAX_LINES + 1)])
    with pytest.raises(EnvironmentFileError, match="bytes"):
        environment.parse(b"#" * (environment.MAX_BYTES + 1))
    with pytest.raises(EnvironmentFileError, match="UTF-8"):
        environment.parse(b"\xff\xfe==1.0\n")


def test_what_is_rendered_is_what_is_parsed():
    '''A builder writes its own file from what parsed; it reads back the same.'''
    parsed = parse("numpy==2.0.1", "pyuvm==3.0.0 ; sys_platform == 'linux'")

    again = environment.parse(environment.render(
        parsed.pins, header="written by the builder").encode())

    assert again == parsed


###########################
# At submit
###########################

pytest.importorskip("flask", reason="the server extra is not installed")


def carrying(job_archive, text, node=("stepone", "0")):
    return job_archive(extra={environment.path_for(*node): text.encode()})


def submitted(server_client, key, token, archive):
    from test_server_jobs import stage, submit

    path, digest, size = archive
    job = stage(server_client, key, token, path, size)
    return outcome(server_client, key, token,
                   submit(server_client, key, token, job["id"], digest, size))


def slug(response):
    return (response.get_json().get("type") or "").rsplit("/", 1)[-1]


@pytest.fixture
def installed(monkeypatch, tmp_path):
    '''Host mode's install while staging, without pip: what it was asked
    for, and a site of its own for each.'''
    from siliconcompiler.remote.server import envinstall

    asked = []

    def install(parsed, root, logger, node, constrain=(), indexes=()):
        asked.append((node, [str(pin) for pin in parsed.pins], list(indexes)))
        site = tmp_path / "sites" / f"{node[0]}-{node[1]}"
        site.mkdir(parents=True, exist_ok=True)
        return str(site)

    monkeypatch.setattr(envinstall, "install", install)
    return asked


@pytest.fixture
def builds(server, installed):
    '''A deployment that advertises `python.env`, with nodes on this host:
    each environment is installed while the job stages.'''
    server.config["SC_CONFIG"]._values["features"] = \
        server.config["SC_CONFIG"]["features"] + ["python.env"]
    return server


def test_a_job_carrying_an_environment_needs_python_env(
        server, server_client, key, token, job_archive):
    '''The file's presence is the declaration: the backstop for a job that did
    not say so at create.'''
    response = submitted(server_client, key, token,
                         carrying(job_archive, "numpy==2.0.1\n"))

    assert response.status_code == 501
    assert (slug(response), response.get_json()["feature"]) == \
        ("feature-unsupported", "python.env")


def test_a_line_outside_the_format_is_an_archive_refusal(
        builds, server_client, key, token, job_archive):
    response = submitted(server_client, key, token,
                         carrying(job_archive, "numpy>=2.0\n"))

    assert response.status_code == 422
    assert slug(response) == "archive-rejected"
    assert response.get_json()["reason"] == "environment_file"
    assert "line 1" in response.get_json()["detail"]


def test_a_file_for_no_node_is_refused(builds, server_client, key, token, job_archive):
    response = submitted(server_client, key, token,
                         carrying(job_archive, "numpy==2.0.1\n", node=("nosuch", "0")))

    assert response.get_json()["reason"] == "environment_file"


def test_a_file_naming_an_index_is_an_archive_refusal(
        builds, server_client, key, token, job_archive):
    '''`index-not-allowed` is gone: no line may name an index at all.'''
    response = submitted(server_client, key, token, carrying(
        job_archive, "--extra-index-url https://pkgs.example.com/simple/\nnumpy==2.0.1\n"))

    assert response.status_code == 422
    assert slug(response) == "archive-rejected"
    assert response.get_json()["reason"] == "environment_file"


def test_a_well_formed_environment_is_installed_while_staging(
        builds, installed, server_client, key, token, job_archive, dispatcher):
    '''From the deployment's own indexes, never the job's.'''
    response = submitted(server_client, key, token, carrying(
        job_archive, "# generated\nnumpy==2.0.1\n"))

    assert response.status_code == 202, response.get_json()
    assert installed == [(("stepone", "0"), ["numpy==2.0.1"], ["https://pypi.org/simple/"])]
    assert dispatcher.submitted


def test_a_node_the_run_does_not_execute_gets_no_file(
        builds, server_client, key, token, nop_project, job_archive):
    '''A file for a node the flow has and the run does not execute is
    refused too.'''
    nop_project.set("option", "to", "stepone")
    response = submitted(server_client, key, token, carrying(
        job_archive, "numpy==2.0.1\n", node=("steptwo", "0")))

    assert response.get_json()["reason"] == "environment_file"


def test_uploaded_packages_need_no_python_env(
        server, server_client, key, token, job_archive, dispatcher):
    '''🔴 The user's own code is accepted without `python.env` and without an
    environment file, and never parsed.'''
    assert "python.env" not in server.config["SC_CONFIG"]["features"]
    archive = job_archive(extra={
        f"{environment.packages_path()}/helpers.py": b"def bench(): pass\n",
        f"{environment.packages_path()}/mylib/__init__.py": b"this is not parsed (",
    })

    response = submitted(server_client, key, token, archive)

    assert response.status_code == 202, response.get_json()
    assert dispatcher.submitted


def test_the_deployment_does_not_advertise_what_it_cannot_build(tmp_path):
    '''No builder yet: where nodes run in containers there is nothing to
    build an environment with.'''
    from siliconcompiler.remote.server.config import Config

    (tmp_path / "config.json").write_text(json.dumps(
        {"features": ["python.env"], "containers": True}))
    with pytest.raises(ValueError, match="python.env"):
        Config.load(tmp_path)


@pytest.fixture
def dispatcher(server):
    from test_server_jobs import FakeDispatcher

    fake = FakeDispatcher()
    server.config["SC_JOBS"]._dispatcher = fake
    return fake


###########################
# End to end, over an extracted upload
###########################

@pytest.fixture
def host_pip(monkeypatch):
    '''pip, and nothing else, stood in for: what it was asked to install, and
    an environment that holds it.'''
    from siliconcompiler.remote.server import pipbuild

    asked = []

    def install(requirements, site, constrain=(), proxy_socket=None, echo=None,
                indexes=(), allow_source=False):
        asked.append((open(requirements).read(), list(indexes), allow_source))
        import os
        os.makedirs(os.path.join(site, "numpy"))
        open(os.path.join(site, "numpy", "__init__.py"), "w").write("")
        return {"returncode": 0, "python": "cpython-test", "version": "3",
                "platform": "test", "installed": [["numpy", "2.0.1"]]}

    monkeypatch.setattr(pipbuild, "install", install)
    return asked


def test_an_upload_carrying_python_runs_to_the_end(server, server_client, key, token,
                                                   job_archive, host_pip):
    '''🔴 One upload through every step for real but pip: extracted; its file
    held to the format and installed while staging, wheels only, from the
    deployment's indexes, into the user's own cache; linked where the node's
    task looks; the user's code left where the run's tree has it; dispatched
    here; and run to the end.'''
    import time

    from conftest import call

    server.config["SC_CONFIG"]._values["features"] = \
        server.config["SC_CONFIG"]["features"] + ["python.env"]
    archive = job_archive(extra={
        environment.path_for("stepone", "0"): b"# generated\nnumpy==2.0.1\n",
        f"{environment.packages_path()}/helpers.py": b"VALUE = 1\n"})

    response = submitted(server_client, key, token, archive)
    assert response.status_code == 202, response.get_json()
    job_id = response.get_json()["id"]

    deadline = time.monotonic() + 120
    while True:
        job = call(server_client, key, "GET", f"/v1/jobs/{job_id}", token).get_json()
        if job["terminal"] or time.monotonic() > deadline:
            break
        time.sleep(0.5)
    assert job["state"] == "completed", job

    (text, indexes, from_source), = host_pip
    assert "numpy==2.0.1" in text.splitlines() and not from_source
    assert indexes == ["https://pypi.org/simple/"]

    jobs = server.config["SC_JOBS"]
    tree = jobs.job_root(job["owner"]["id"], job_id) / "gcd" / "job0"
    site = tree / environment.site_path("stepone", "0")
    assert site.is_symlink()
    assert str(site.resolve()).startswith(str(jobs.cache_dir(job["owner"]["id"]).resolve()))
    assert (site / "numpy" / "__init__.py").is_file()
    assert (tree / environment.packages_path() / "helpers.py").read_text() == "VALUE = 1\n"


@pytest.mark.parametrize("output,expected", [
    ("ERROR: No matching distribution found for numpy==2.0.1", "uninstallable"),
    ("WARNING: Retrying (Retry(total=4)) after connection broken by "
     "'NewConnectionError'\nERROR: No matching distribution found for numpy==2.0.1",
     "staging-failed"),
])
def test_a_line_that_will_not_install_rejects_the_job_before_any_node_runs(
        server, server_client, key, token, job_archive, dispatcher, monkeypatch,
        output, expected):
    '''🔴 Host mode installs while staging, so a line that will not install is
    `rejected`, `software-unavailable`, `uninstallable`, naming the package and
    the target -- not a failed run. An index that does not answer is this
    server's failure: `failed`, `staging-failed`.'''
    from conftest import call
    from siliconcompiler.remote.server import pipbuild

    def install(requirements, site, constrain=(), proxy_socket=None, echo=None,
                indexes=(), allow_source=False):
        return {"returncode": 1, "python": "cpython-test", "version": "3",
                "platform": "test-platform", "unresolved": pipbuild.named(output),
                "network": bool(pipbuild._NETWORK.search(output)), "tail": output}

    monkeypatch.setattr(pipbuild, "install", install)
    server.config["SC_CONFIG"]._values["features"] = \
        server.config["SC_CONFIG"]["features"] + ["python.env"]

    from test_server_jobs import stage, submit

    path, digest, size = carrying(job_archive, "numpy==2.0.1\n")
    created = stage(server_client, key, token, path, size)
    submit(server_client, key, token, created["id"], digest, size)
    job = call(server_client, key, "GET", f"/v1/jobs/{created['id']}", token).get_json()

    error = job["error"]
    if expected == "uninstallable":
        assert job["state"] == "rejected"
        assert (error["type"].rsplit("/", 1)[-1], error["reason"]) == \
            ("software-unavailable", "uninstallable")
        assert error["unresolved"][0]["name"] == "numpy"
        assert "cpython-test" in error["detail"] and "test-platform" in error["detail"]
    else:
        assert job["state"] == "failed"
        assert error["type"].endswith("/staging-failed")
    assert not dispatcher.submitted


@pytest.mark.parametrize("containers,available", [(False, []), (True, [])])
def test_a_python_name_nothing_here_holds_is_refused_at_create(
        server, server_client, key, token, containers, available):
    '''🔴 A server never ignores a listed name: host mode answers from its
    own Python, and where nodes run in containers, from the live images.'''
    from conftest import call

    server.config["SC_CONFIG"]._values["containers"] = containers
    response = call(server_client, key, "POST", "/v1/jobs", token, json={
        "design": "gcd", "jobname": "job0",
        "descriptor": {"requires": {"python": {"scnosuchdistribution": ["==1.0"]}}}})

    assert response.status_code == 422, response.get_json()
    body = response.get_json()
    assert slug(response) == "software-unavailable"
    assert body["unresolved"] == [{"name": "scnosuchdistribution",
                                   "requirement": ["==1.0"], "available": available}]


def test_host_mode_answers_from_its_own_python(server, server_client, key, token):
    from importlib.metadata import version

    from conftest import call

    ok = call(server_client, key, "POST", "/v1/jobs", token, json={
        "design": "gcd", "jobname": "job0",
        "descriptor": {"requires": {"python": {"packaging": [f"=={version('packaging')}"]}}}})
    assert ok.status_code == 201, ok.get_json()

    other = call(server_client, key, "POST", "/v1/jobs", token, json={
        "design": "gcd", "jobname": "job1",
        "descriptor": {"requires": {"python": {"packaging": ["==0.0.1"]}}}})
    assert other.status_code == 422
    assert other.get_json()["unresolved"][0]["available"] == [version("packaging")]


def test_bare_slurm_with_no_builder_offers_no_python_env(tmp_path):
    from siliconcompiler.remote.server.app import create_app

    (tmp_path / "config.json").write_text(
        json.dumps({"features": ["logs.stream", "python.env"]}))
    with pytest.raises(ValueError, match="python.env"):
        create_app(tmp_path, cluster="slurm")
